export const labReportData = {
  id: 1,
  patient_id: 1,
  patient: {
    name: "John Doe",
    age: "30",
    gender: "male",
  },
  doctor_name: "Aung Aung",
  sample_id: 1,
  sample_type: "String",
  patient_type: "String",
  test_date: "2022-2-2",
};

export const labResultData = [
  {
    id: 1,
    lab_report_id: 1,
    parameter_name: "Na",
    test_name: "Electrolyte",
    parameter_id: 1,
    result: "10",
    unit: "mmol/L",
    upper_limit: "8",
    lower_limit: "11",
    remark: "Over",
  },
  {
    id: 2,
    lab_report_id: 1,
    parameter_name: "Ca",
    test_name: "Electrolyte",
    parameter_id: 2,
    result: "10",
    unit: "mmol/L",
    upper_limit: "8",
    lower_limit: "11",
    remark: "Over",
  },
  {
    id: 3,
    lab_report_id: 1,
    parameter_name: "K",
    test_name: "Electrolyte",
    parameter_id: 3,
    result: "10",
    unit: "mmol/L",
    upper_limit: "8",
    lower_limit: "11",
    remark: "Over",
  },
  {
    id: 4,
    lab_report_id: 1,
    parameter_name: "ABO Grouping",
    test_name: "ABO Grouping",
    parameter_id: 4,
    result: "A",
    unit: null,
    upper_limit: null,
    lower_limit: null,
    remark: null,
  },
  {
    id: 5,
    lab_report_id: 1,
    parameter_name: "Rh Grouping",
    test_name: "ABO Grouping",
    parameter_id: 5,
    result: "Positive",
    unit: null,
    upper_limit: null,
    lower_limit: null,
    remark: null,
  },
];
